#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace GAS.Editor.TagSystem
{
    /// <summary>
    /// [A2] GameplayTags 程式碼生成器 — 從 GameplayTagLibrary.asset 自動產出 GameplayTags.generated.cs。
    /// 觸發點:
    ///   1. 選單 GAS/Tag System/[A2] Regenerate GameplayTags.cs (手動)
    ///   2. GameplayTagAssetPostprocessor 偵測 Library 變動 (自動)
    /// 第一次執行時會自動把舊版手寫的 GameplayTags 靜態類從 GameplayTagLibrary.cs 移除,並備份原始碼。
    /// </summary>
    public static class GameplayTagCodeGenerator
    {
        private const string LIBRARY_PATH = "Assets/Resources/GameplayTagLibrary.asset";
        private const string OUTPUT_PATH = "Assets/Script/GAS/Tags/GameplayTags.generated.cs";
        private const string LEGACY_SOURCE_PATH = "Assets/Script/GAS/Tags/GameplayTagLibrary.cs";
        private const string LEGACY_BACKUP_FOLDER = "Assets/Script/GAS/Tags/Backups";

        private const string AUTO_GEN_HEADER_MARKER = "// <auto-generated>";

        // ====================================================================
        // MenuItem 入口
        // ====================================================================

        [MenuItem("GAS/Tag System/[A2] Regenerate GameplayTags.cs", priority = 2)]
        public static void RegenerateMenu()
        {
            GameplayTagLibrary library = AssetDatabase.LoadAssetAtPath<GameplayTagLibrary>(LIBRARY_PATH);
            if (library == null)
            {
                EditorUtility.DisplayDialog(
                    "找不到 Tag Library",
                    $"預期路徑: {LIBRARY_PATH}",
                    "知道了");
                return;
            }

            GenerationResult result = RunGeneration(library);
            string title = result.Success ? "GameplayTags.cs 已重新生成" : "生成失敗";
            EditorUtility.DisplayDialog(title, result.ToReportString(), "好");

            if (result.Success && File.Exists(OUTPUT_PATH))
            {
                UnityEngine.Object generated = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(OUTPUT_PATH);
                if (generated != null)
                {
                    EditorGUIUtility.PingObject(generated);
                }
            }
        }

        /// <summary>
        /// 提供給 AssetPostprocessor 呼叫的靜默版本(無確認 / 無結果視窗,只在出錯時 Console 警告)。
        /// </summary>
        public static GenerationResult RegenerateSilent(GameplayTagLibrary library)
        {
            return RunGeneration(library);
        }

        // ====================================================================
        // 主流程
        // ====================================================================

        public sealed class GenerationResult
        {
            public bool Success;
            public int TagCount;
            public int DescCount;
            public bool CleanupPerformed;
            public string CleanupBackupPath;
            public List<string> Errors = new();
            public List<string> Warnings = new();

            public string ToReportString()
            {
                StringBuilder sb = new();
                if (Success)
                {
                    sb.AppendLine($"已生成 {TagCount} 個 Tag 常數 (含 {DescCount} 條說明)。");
                    sb.AppendLine($"輸出: {OUTPUT_PATH}");
                    if (CleanupPerformed)
                    {
                        sb.AppendLine();
                        sb.AppendLine("過渡動作: 已自動移除 GameplayTagLibrary.cs 中的舊 GameplayTags 靜態類。");
                        sb.AppendLine($"原始碼備份: {CleanupBackupPath}");
                    }
                }
                else
                {
                    sb.AppendLine("生成已中止。");
                }
                if (Errors.Count > 0)
                {
                    sb.AppendLine();
                    sb.AppendLine("錯誤:");
                    foreach (string e in Errors)
                    {
                        sb.Append("  • ").AppendLine(e);
                    }
                }
                if (Warnings.Count > 0)
                {
                    sb.AppendLine();
                    sb.AppendLine("警告:");
                    foreach (string w in Warnings)
                    {
                        sb.Append("  • ").AppendLine(w);
                    }
                }
                return sb.ToString().TrimEnd();
            }
        }

        private static GenerationResult RunGeneration(GameplayTagLibrary library)
        {
            GenerationResult result = new();

            // 1. 取 Tag 清單
            List<GameplayTagLibrary.TagDefinition> defs = library.TagDefinitions != null
                ? library.TagDefinitions.ToList()
                : new List<GameplayTagLibrary.TagDefinition>();
            if (defs.Count == 0)
            {
                result.Errors.Add("Library 沒有任何 Tag,無法生成。");
                return result;
            }

            // 2. 驗證 Tag 名稱
            List<GameplayTagLibrary.TagDefinition> validDefs = ValidateDefinitions(defs, result);
            if (result.Errors.Count > 0)
            {
                return result;
            }

            // 3. 建 Trie
            TagNode root = BuildTrie(validDefs);

            // 4. 產出程式碼
            string code = EmitCode(root, validDefs.Count);

            // 5. 寫入檔案(避免無變動寫入 → 不必要的 import)
            bool writeOk = WriteIfChanged(OUTPUT_PATH, code);
            if (!writeOk)
            {
                result.Errors.Add($"無法寫入 {OUTPUT_PATH}");
                return result;
            }

            // 6. 一次性過渡:若 GameplayTagLibrary.cs 還有舊靜態類,移除並備份
            bool cleanupHappened = TryRemoveLegacyStaticClass(out string backupPath, out string cleanupError);
            result.CleanupPerformed = cleanupHappened;
            result.CleanupBackupPath = backupPath;
            if (!string.IsNullOrEmpty(cleanupError))
            {
                result.Warnings.Add(cleanupError);
            }

            // 7. 統計與 import
            result.TagCount = validDefs.Count;
            result.DescCount = validDefs.Count(d => !string.IsNullOrEmpty(d.Description));
            result.Success = true;

            AssetDatabase.ImportAsset(OUTPUT_PATH, ImportAssetOptions.ForceUpdate);
            if (cleanupHappened)
            {
                AssetDatabase.ImportAsset(LEGACY_SOURCE_PATH, ImportAssetOptions.ForceUpdate);
            }

            Debug.Log($"[GameplayTagCodeGenerator] 已生成 {result.TagCount} 個 Tag → {OUTPUT_PATH}");
            return result;
        }

        // ====================================================================
        // 驗證
        // ====================================================================

        private static readonly HashSet<string> CSHARP_KEYWORDS = new(StringComparer.Ordinal)
        {
            "abstract","as","base","bool","break","byte","case","catch","char","checked",
            "class","const","continue","decimal","default","delegate","do","double","else",
            "enum","event","explicit","extern","false","finally","fixed","float","for",
            "foreach","goto","if","implicit","in","int","interface","internal","is","lock",
            "long","namespace","new","null","object","operator","out","override","params",
            "private","protected","public","readonly","ref","return","sbyte","sealed",
            "short","sizeof","stackalloc","static","string","struct","switch","this","throw",
            "true","try","typeof","uint","ulong","unchecked","unsafe","ushort","using",
            "virtual","void","volatile","while"
        };

        private static List<GameplayTagLibrary.TagDefinition> ValidateDefinitions(
            List<GameplayTagLibrary.TagDefinition> defs, GenerationResult result)
        {
            HashSet<string> seen = new();
            List<GameplayTagLibrary.TagDefinition> valid = new();
            foreach (GameplayTagLibrary.TagDefinition d in defs)
            {
                string name = d?.TagName;
                if (string.IsNullOrWhiteSpace(name))
                {
                    result.Warnings.Add("略過: 空白 TagName");
                    continue;
                }
                if (!seen.Add(name))
                {
                    result.Warnings.Add($"略過重複: '{name}'");
                    continue;
                }
                string[] segs = name.Split('.');
                bool segOk = true;
                foreach (string seg in segs)
                {
                    if (!IsValidSegment(seg))
                    {
                        result.Errors.Add($"非法 Tag 段: '{seg}' (來自 '{name}') — 段內僅允許字母/數字/底線,且不可數字開頭。");
                        segOk = false;
                    }
                }
                if (!segOk)
                {
                    continue;
                }
                valid.Add(d);
            }
            return valid;
        }

        private static bool IsValidSegment(string seg)
        {
            if (string.IsNullOrEmpty(seg))
            {
                return false;
            }
            char first = seg[0];
            if (!(char.IsLetter(first) || first == '_'))
            {
                return false;
            }
            for (int i = 1; i < seg.Length; i++)
            {
                char c = seg[i];
                if (!(char.IsLetterOrDigit(c) || c == '_'))
                {
                    return false;
                }
            }
            return true;
        }

        /// <summary>給 segment 字串轉成合法 C# 識別子 — 關鍵字加 @ 跳脫。</summary>
        private static string ToCSharpIdentifier(string seg)
        {
            return CSHARP_KEYWORDS.Contains(seg) ? "@" + seg : seg;
        }

        // ====================================================================
        // Trie
        // ====================================================================

        private sealed class TagNode
        {
            public string Segment = string.Empty;
            public string FullPath = string.Empty;
            public string Description = string.Empty;
            public bool IsTag;
            public SortedDictionary<string, TagNode> Children = new(StringComparer.Ordinal);
        }

        private static TagNode BuildTrie(List<GameplayTagLibrary.TagDefinition> defs)
        {
            TagNode root = new();
            foreach (GameplayTagLibrary.TagDefinition d in defs)
            {
                string[] segs = d.TagName.Split('.');
                TagNode current = root;
                for (int i = 0; i < segs.Length; i++)
                {
                    string seg = segs[i];
                    if (!current.Children.TryGetValue(seg, out TagNode child))
                    {
                        child = new TagNode
                        {
                            Segment = seg,
                            FullPath = i == 0 ? seg : current.FullPath + "." + seg
                        };
                        current.Children[seg] = child;
                    }
                    current = child;
                }
                current.IsTag = true;
                current.Description = d.Description ?? string.Empty;
            }
            return root;
        }

        // ====================================================================
        // 程式碼產出
        // ====================================================================

        private static string EmitCode(TagNode root, int totalCount)
        {
            StringBuilder sb = new();
            sb.AppendLine(AUTO_GEN_HEADER_MARKER);
            sb.AppendLine("//   此檔由 GameplayTagCodeGenerator 自動從 GameplayTagLibrary.asset 產出。");
            sb.AppendLine("//   *** 不要手動編輯 *** — 任何修改都會在下次 Library 存檔時被覆寫。");
            sb.AppendLine("//   要新增/重命名 Tag,請編輯 GameplayTagLibrary.asset。");
            sb.AppendLine($"//   產出於: {DateTime.Now:yyyy-MM-dd HH:mm:ss}    Tag 總數: {totalCount}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace GAS");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 由 GameplayTagLibrary.asset 自動生成的 Tag 常數類。");
            sb.AppendLine("    /// 編輯 Library 後存檔即自動重生此檔。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class GameplayTags");
            sb.AppendLine("    {");
            foreach (TagNode child in root.Children.Values)
            {
                EmitNode(sb, child, indent: 2);
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitNode(StringBuilder sb, TagNode node, int indent)
        {
            string pad = new(' ', indent * 4);
            string id = ToCSharpIdentifier(node.Segment);
            bool hasChildren = node.Children.Count > 0;

            if (!hasChildren)
            {
                // 葉子: 只是個 readonly 欄位
                EmitDocComment(sb, node.Description, pad);
                sb.Append(pad).Append("public static readonly GameplayTag ").Append(id)
                  .Append(" = new(\"").Append(node.FullPath).AppendLine("\");");
                return;
            }

            // 有子節點 → 內嵌類別
            EmitDocComment(sb, node.Description, pad);
            sb.Append(pad).Append("public static class ").AppendLine(id);
            sb.Append(pad).AppendLine("{");
            if (node.IsTag)
            {
                // 同時自己也是個 Tag → 加 Root 欄位
                sb.Append(pad).Append("    public static readonly GameplayTag Root = new(\"")
                  .Append(node.FullPath).AppendLine("\");");
            }
            foreach (TagNode child in node.Children.Values)
            {
                EmitNode(sb, child, indent + 1);
            }
            sb.Append(pad).AppendLine("}");
        }

        private static void EmitDocComment(StringBuilder sb, string desc, string pad)
        {
            if (string.IsNullOrWhiteSpace(desc))
            {
                return;
            }
            // 換行替換為空格(Library 中 Description 已壓成單行,但保險)
            string oneLine = desc.Replace("\r", " ").Replace("\n", " ").Trim();
            sb.Append(pad).Append("/// <summary>").Append(EscapeXml(oneLine)).AppendLine("</summary>");
        }

        private static string EscapeXml(string s)
        {
            return s
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }

        // ====================================================================
        // 檔案寫入
        // ====================================================================

        private static bool WriteIfChanged(string path, string newContent)
        {
            try
            {
                if (File.Exists(path))
                {
                    string old = File.ReadAllText(path);
                    if (string.Equals(old, newContent, StringComparison.Ordinal))
                    {
                        return true; // 無變動,視為成功
                    }
                }
                Directory.CreateDirectory(Path.GetDirectoryName(path));
                File.WriteAllText(path, newContent);
                return true;
            }
            catch (Exception e)
            {
                Debug.LogError($"[GameplayTagCodeGenerator] 寫入失敗: {e}");
                return false;
            }
        }

        // ====================================================================
        // 過渡: 移除 GameplayTagLibrary.cs 後半的舊靜態類
        // ====================================================================

        private static bool TryRemoveLegacyStaticClass(out string backupPath, out string errorMsg)
        {
            backupPath = null;
            errorMsg = null;

            if (!File.Exists(LEGACY_SOURCE_PATH))
            {
                return false;
            }
            string source = File.ReadAllText(LEGACY_SOURCE_PATH);
            int classIdx = source.IndexOf("public static class GameplayTags", StringComparison.Ordinal);
            if (classIdx < 0)
            {
                return false; // 已經移除過
            }

            // 1. 往前找連續 /// 行 (XML doc) — 以「整行」為單位往上掃,避免抓到 indent 空白誤判
            int classLineStart = source.LastIndexOf('\n', classIdx - 1) + 1;
            int blockStart = classLineStart;
            int searchLineEnd = classLineStart - 1; // 上一行的 \n 位置(若 classLineStart=0 則為 -1,迴圈不進)
            while (searchLineEnd > 0)
            {
                int prevLineStart = source.LastIndexOf('\n', searchLineEnd - 1) + 1;
                string line = source.Substring(prevLineStart, searchLineEnd - prevLineStart).TrimStart();
                if (line.StartsWith("///", StringComparison.Ordinal))
                {
                    blockStart = prevLineStart;
                    searchLineEnd = prevLineStart - 1;
                }
                else
                {
                    break;
                }
            }

            // 2. 找開頭 { 並做大括號平衡
            int openBrace = source.IndexOf('{', classIdx);
            if (openBrace < 0)
            {
                errorMsg = "找到舊靜態類但找不到開頭 '{',未移除。";
                return false;
            }
            int depth = 1;
            int pos = openBrace + 1;
            while (pos < source.Length && depth > 0)
            {
                char c = source[pos];
                if (c == '{')
                {
                    depth++;
                }
                else if (c == '}')
                {
                    depth--;
                }
                pos++;
            }
            if (depth != 0)
            {
                errorMsg = "大括號不平衡,未移除舊靜態類。";
                return false;
            }
            int classEnd = pos; // pos 已是結尾 '}' 之後

            // 3. 備份
            try
            {
                if (!AssetDatabase.IsValidFolder(LEGACY_BACKUP_FOLDER))
                {
                    Directory.CreateDirectory(LEGACY_BACKUP_FOLDER);
                    AssetDatabase.Refresh();
                }
                string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
                backupPath = $"{LEGACY_BACKUP_FOLDER}/GameplayTagLibrary.preA2_{timestamp}.cs.txt";
                File.WriteAllText(backupPath, source);
            }
            catch (Exception e)
            {
                errorMsg = $"備份失敗,未移除: {e.Message}";
                return false;
            }

            // 4. 移除舊靜態類段,清整前後空行
            string before = source.Substring(0, blockStart).TrimEnd();
            string after = source.Substring(classEnd).TrimStart();
            // 一般 after 是 "\n}\n" (namespace 關閉)
            string rewritten = before + "\n}\n";
            // 若 after 還含其他內容(理論上不應該),保留
            string remainderAfterNs = after.StartsWith("}") ? after.Substring(1).TrimStart() : after;
            if (!string.IsNullOrEmpty(remainderAfterNs))
            {
                rewritten += "\n" + remainderAfterNs;
            }

            try
            {
                File.WriteAllText(LEGACY_SOURCE_PATH, rewritten);
            }
            catch (Exception e)
            {
                errorMsg = $"寫入移除後檔案失敗: {e.Message}";
                return false;
            }
            return true;
        }
    }
}
#endif
