// <auto-generated>
//   此檔由 GameplayTagCodeGenerator 自動從 GameplayTagLibrary.asset 產出。
//   *** 不要手動編輯 *** — 任何修改都會在下次 Library 存檔時被覆寫。
//   要新增/重命名 Tag,請編輯 GameplayTagLibrary.asset。
//   產出於: 2026-05-14 07:21:04    Tag 總數: 75
// </auto-generated>

namespace GAS
{
    /// <summary>
    /// 由 GameplayTagLibrary.asset 自動生成的 Tag 常數類。
    /// 編輯 Library 後存檔即自動重生此檔。
    /// </summary>
    public static class GameplayTags
    {
        public static class Ability
        {
            public static readonly GameplayTag Root = new("Ability");
            public static class Assist
            {
                public static readonly GameplayTag Root = new("Ability.Assist");
                public static readonly GameplayTag Dodge = new("Ability.Assist.Dodge");
                public static readonly GameplayTag Parry = new("Ability.Assist.Parry");
            }
            public static class Attack
            {
                public static readonly GameplayTag Root = new("Ability.Attack");
                public static readonly GameplayTag Heavy = new("Ability.Attack.Heavy");
                public static readonly GameplayTag Light = new("Ability.Attack.Light");
                public static readonly GameplayTag Melee = new("Ability.Attack.Melee");
                public static class Ranged
                {
                    public static readonly GameplayTag Root = new("Ability.Attack.Ranged");
                    public static readonly GameplayTag Heavy = new("Ability.Attack.Ranged.Heavy");
                    public static readonly GameplayTag Light = new("Ability.Attack.Ranged.Light");
                }
            }
            public static class Movement
            {
                public static readonly GameplayTag Root = new("Ability.Movement");
                public static readonly GameplayTag Dash = new("Ability.Movement.Dash");
                public static readonly GameplayTag Dodge = new("Ability.Movement.Dodge");
                public static readonly GameplayTag Glide = new("Ability.Movement.Glide");
                public static readonly GameplayTag Jump = new("Ability.Movement.Jump");
            }
            public static readonly GameplayTag Skill = new("Ability.Skill");
            public static class Weapon
            {
                public static readonly GameplayTag Root = new("Ability.Weapon");
                public static readonly GameplayTag Switch = new("Ability.Weapon.Switch");
            }
        }
        public static class Cue
        {
            public static readonly GameplayTag Root = new("Cue");
            public static readonly GameplayTag Attack = new("Cue.Attack");
            /// <summary>由 Validator 批次補入 (原 .asset 已引用)</summary>
            public static readonly GameplayTag Dash = new("Cue.Dash");
            public static readonly GameplayTag Dodge = new("Cue.Dodge");
            public static class Hit
            {
                /// <summary>由 Validator 批次補入 (原 .asset 已引用)</summary>
                public static readonly GameplayTag Slash = new("Cue.Hit.Slash");
                public static class Staff
                {
                    /// <summary>由 Validator 批次補入 (原 .asset 已引用)</summary>
                    public static readonly GameplayTag Ice = new("Cue.Hit.Staff.Ice");
                }
            }
            public static readonly GameplayTag HitImpact = new("Cue.HitImpact");
            /// <summary>由 Validator 批次補入 (原 .asset 已引用)</summary>
            public static readonly GameplayTag IceRain_Hit = new("Cue.IceRain_Hit");
            public static class PerfectDodge
            {
                public static readonly GameplayTag Root = new("Cue.PerfectDodge");
                public static readonly GameplayTag BulletTimeEnd = new("Cue.PerfectDodge.BulletTimeEnd");
            }
            public static class Staff
            {
                public static class Muzzle
                {
                    /// <summary>由 Validator 批次補入 (原 .asset 已引用)</summary>
                    public static readonly GameplayTag Ice = new("Cue.Staff.Muzzle.Ice");
                }
            }
            public static class Sword
            {
                /// <summary>由 Validator 批次補入 (原 .asset 已引用)</summary>
                public static readonly GameplayTag Slash = new("Cue.Sword.Slash");
            }
        }
        public static class Effect
        {
            public static readonly GameplayTag Root = new("Effect");
            public static class Buff
            {
                public static readonly GameplayTag Root = new("Effect.Buff");
                public static readonly GameplayTag AttackUp = new("Effect.Buff.AttackUp");
                public static readonly GameplayTag DefenseUp = new("Effect.Buff.DefenseUp");
                public static readonly GameplayTag SpeedUp = new("Effect.Buff.SpeedUp");
            }
            public static class Cooldown
            {
                /// <summary>由 Validator 批次補入 (原 .asset 已引用)</summary>
                public static readonly GameplayTag Dodge = new("Effect.Cooldown.Dodge");
            }
            public static class Cost
            {
                /// <summary>由 Validator 批次補入 (原 .asset 已引用)</summary>
                public static readonly GameplayTag Dodge = new("Effect.Cost.Dodge");
            }
            public static class Damage
            {
                public static readonly GameplayTag Root = new("Effect.Damage");
                public static readonly GameplayTag Fire = new("Effect.Damage.Fire");
                public static readonly GameplayTag Ice = new("Effect.Damage.Ice");
                public static readonly GameplayTag Magical = new("Effect.Damage.Magical");
                public static readonly GameplayTag Physical = new("Effect.Damage.Physical");
            }
            public static class Debuff
            {
                public static readonly GameplayTag Root = new("Effect.Debuff");
                public static readonly GameplayTag AttackDown = new("Effect.Debuff.AttackDown");
                public static readonly GameplayTag DefenseDown = new("Effect.Debuff.DefenseDown");
                public static readonly GameplayTag Slow = new("Effect.Debuff.Slow");
            }
        }
        public static class Event
        {
            public static readonly GameplayTag Root = new("Event");
            public static readonly GameplayTag HitWindow = new("Event.HitWindow");
            public static readonly GameplayTag Montage = new("Event.Montage");
        }
        public static class State
        {
            public static readonly GameplayTag Root = new("State");
            public static readonly GameplayTag AfterImage = new("State.AfterImage");
            public static readonly GameplayTag Aiming = new("State.Aiming");
            /// <summary>玩家光標 AoE 控制中 — 移動鍵改為操作 cursor 位置,Locomotion 看到此 tag 跳過 Update</summary>
            public static readonly GameplayTag AoECursorControl = new("State.AoECursorControl");
            public static readonly GameplayTag AssistWindow = new("State.AssistWindow");
            public static readonly GameplayTag AttackNonCancellable = new("State.AttackNonCancellable");
            public static readonly GameplayTag Attacking = new("State.Attacking");
            public static readonly GameplayTag BulletTime = new("State.BulletTime");
            public static readonly GameplayTag CannotAttack = new("State.CannotAttack");
            public static readonly GameplayTag CannotMove = new("State.CannotMove");
            public static readonly GameplayTag Charging = new("State.Charging");
            public static readonly GameplayTag Dead = new("State.Dead");
            public static readonly GameplayTag DodgeNonCancellable = new("State.DodgeNonCancellable");
            public static readonly GameplayTag Dodging = new("State.Dodging");
            public static readonly GameplayTag Gliding = new("State.Gliding");
            public static readonly GameplayTag HitStunned = new("State.HitStunned");
            public static readonly GameplayTag Invincible = new("State.Invincible");
            public static readonly GameplayTag Jumping = new("State.Jumping");
            public static readonly GameplayTag Parrying = new("State.Parrying");
            public static readonly GameplayTag PerfectDodgeBulletTime = new("State.PerfectDodgeBulletTime");
            public static readonly GameplayTag PerfectDodgeCounterWindow = new("State.PerfectDodgeCounterWindow");
            public static readonly GameplayTag PerfectDodgeWindow = new("State.PerfectDodgeWindow");
            public static readonly GameplayTag Stunned = new("State.Stunned");
            /// <summary>霸體 — 擁有此 Tag 的角色會扣血、會累計 Poise、Poise 擊破時仍會進 Stagger / Knockback; 唯一差別是 Poise 未擊破的小攻擊不播 Flinch,讓當前動作不被打斷。由能力/動畫幀動態添加與移除。 與 Invincible 的差異:Invincible = 完全免疫(含傷害);SuperArmor = 吃傷害 + 吃 Poise,僅免 Flinch。</summary>
            public static readonly GameplayTag SuperArmor = new("State.SuperArmor");
            public static readonly GameplayTag Switching = new("State.Switching");
        }
    }
}
